# NumPy Module
author : Salim Shadman


In [1]:
import numpy as np

In [2]:
# creating array using numpy
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [3]:
# creating array of n-1 whole numbers which tkes n as parameter
np.arange(6)

array([0, 1, 2, 3, 4, 5])

### Time comparision 

In [8]:
# traditional python array
%timeit [i**2 for i in range(1000)]

247 µs ± 8.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
# using numpy
%timeit (np.arange(1000) ** 2)

2.51 µs ± 88.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


From above it is clear that numpy is much faster than traditional array 

## Creating arrays

In [10]:
a = np.array([1,2,3])

In [11]:
a.ndim # dimension of array

1

In [12]:
a.size # number of elements

3

In [13]:
a.shape # shape of array like row depth etc


(3,)

In [15]:
# creating 2d array
b = np.array([
    [1,2,3],[1,2,3],[1,2,3]
])

In [16]:
b.ndim

2

In [17]:
b.shape

(3, 3)

In [18]:
b.size

9

In [19]:
len(b) # tells number of rows

3

In [25]:
# creating 3d array
c = np.array([[[0,1],[0,1]],[[0,1],[0,1]]])

In [26]:
c.ndim

3

In [27]:
c.shape

(2, 2, 2)

In [28]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [29]:
#start end step (ses)

In [36]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# get n numbers between two numbers
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [46]:
np.diag(np.arange(10))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

### Random Module

In [48]:
a = np.random.rand(4)
a

array([0.74020951, 0.40009998, 0.22615494, 0.26708577])

In [50]:
a = np.random.randn(4)
a

array([ 0.95621519, -0.51541202,  1.45487596,  0.91810085])

### dtype usage

In [51]:
np.arange(10,dtype='float64')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
learner = np.array(["Salim","Bhavya","Yash","Pandya"])
learner.dtype

dtype('<U6')

### Indexing and slicing

In [54]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# reversing
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [57]:
# start end step
a[0:5:2]

array([0, 2, 4])

## Fancy Indexing

In [62]:
a = np.random.randint(0,20,10)
a

array([ 1,  1,  4, 14, 11,  4, 14,  9, 11,  7])

In [64]:
b = (a % 2 ) == 0
b

array([False, False,  True,  True, False,  True,  True, False, False,
       False])

In [68]:
c = a[b]
c

array([ 4, 14,  4, 14])

In [69]:
k = np.arange(10)

In [70]:
k[[0,1,2]]

array([0, 1, 2])